-- POLARIS Antarctic Expeditions Seed Data

INSERT INTO expeditions (expedition_id, expedition_name, expedition_code, expedition_year, description, mission_objective, target_region, lead_organization, expedition_leader, start_date, end_date, status, notes, created_by, updated_by)
VALUES
(
    'EXP-2025-044',
    '44th Indian Scientific Expedition to Antarctica',
    'ISEA-44',
    2025,
    'Comprehensive multidisciplinary polar expedition encompassing cryosphere dynamics, atmospheric chemistry, and biological sampling across Eastern Antarctica.',
    'Execute high-precision ice-core drilling at Princess Elizabeth Land, perform structural maintenance on Bharati Station, and conduct Southern Ocean biochemical profiling.',
    'Larsemann Hills (Bharati Station)',
    'NCPOR - National Centre for Polar and Ocean Research',
    'Dr. Shailendra Saini',
    '2025-11-15',
    '2026-04-10',
    'Active',
    'Winter-over team deployed. Satellite telemetry nominal. Automated weather stations relaying continuous data to Goa HQ.',
    'director@ncpor.res.in',
    'logistics@ncpor.res.in'
),
(
    'EXP-2026-045',
    '45th Indian Scientific Expedition to Antarctica',
    'ISEA-45',
    2026,
    'Milestone 45th polar campaign focusing on Maitri-II site ground stabilization, clean solar-wind microgrid installation, and continental ice margin radar sounding.',
    'Complete preliminary engineering works for new Maitri-II station, transport 300 tons of prefabricated structural panels, and establish deep ice GPS markers.',
    'Schirmacher Oasis (Maitri Station)',
    'NCPOR - National Centre for Polar and Ocean Research',
    'Dr. Rajesh Asthana',
    '2026-11-20',
    '2027-03-30',
    'Planned',
    'Environmental impact assessment submitted to Antarctic Treaty Consultative Meeting (ATCM). Cargo consolidation ongoing at Mormugao Port.',
    'director@ncpor.res.in',
    'coordinator@ncpor.res.in'
),
(
    'EXP-2026-002',
    'Amery Ice Shelf Grounding Zone Expedition',
    'AMERY-ICE-01',
    2026,
    'Collaborative deep grounding-line exploration deploying autonomous sub-ice ocean gliders and radar tomography to map oceanic melting rates.',
    'Deploy 4 long-endurance oceanographic profilers into the sub-shelf cavity and retrieve seismic sensor strings across the hinge line.',
    'Amery Ice Shelf',
    'NCPOR & Australian Antarctic Division',
    'Dr. Ananya Mukherjee',
    '2026-12-05',
    '2027-02-25',
    'Approved',
    'Joint logistics protocol ratified. Helicopter reconnaissance flight paths approved by air safety council.',
    'coordinator@ncpor.res.in',
    'director@ncpor.res.in'
),
(
    'EXP-2024-043',
    '43rd Indian Scientific Expedition to Antarctica',
    'ISEA-43',
    2024,
    'Annual summer campaign coupled with continuous winter-over research. Conducted paleoclimate studies through lake sediment coring in Schirmacher Oasis.',
    'Recover 20m sediment cores from Priyadarshini Lake, complete generator overhauls at Bharati, and relief of wintering team.',
    'Larsemann Hills & Maitri',
    'NCPOR - National Centre for Polar and Ocean Research',
    'Dr. Yogesh Ray',
    '2024-11-01',
    '2025-04-05',
    'Completed',
    'All objectives successfully fulfilled. 18 peer-reviewed datasets uploaded to the National Polar Data Center. Scientific team safely demobilized.',
    'director@ncpor.res.in',
    'director@ncpor.res.in'
),
(
    'EXP-2025-019',
    'Weddell Sea Benthic Ecology Survey',
    'WEDDELL-BIO-25',
    2025,
    'Exploratory deep-sea benthic dredge and environmental DNA sampling within the eastern Weddell Sea polynya corridor.',
    'Quantify cold-adapted invertebrate biomass and determine benthic vulnerability to ocean acidification.',
    'Weddell Sea Sector',
    'NCPOR & British Antarctic Survey',
    'Dr. Victor Vance',
    '2025-01-10',
    '2025-03-15',
    'Cancelled',
    'Expedition cancelled in early planning phase due to severe multi-year pack ice obstruction and charter vessel redirection for humanitarian relief.',
    'coordinator@ncpor.res.in',
    'director@ncpor.res.in'
);
